name: heroku

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: akhileshns/heroku-deploy@master # This is the action
        with:
          heroku_api_key: ${{secrets.5559b8d6-c269-4568-8f7d-54e2bbb601eb}}
          heroku_app_name: "buyyoutubecompany" #Must be unique in Heroku
          heroku_email: ${{secrets.tfghjhtyujh56765tyy@protonmail.com}}
          usedocker: true
